title: "Compendium"
author: "okaycasual"
description: "A searchable D&D 5e lists."
url: "https://okaycasual.github.io"
source-url: "https://github.com/okaycasual/ck"
baseurl: "/ck"
exclude: ['Rakefile', 'README.md']
collections:
  monsters:
    output: true
    permalink: "/monsters/:name"
  items:
    output: true
    permalink: "/item/:name"
  companions:
    output: true
    permalink: "/companion/:name"
  tags:
    output: true
    permalink: "/tag/:name"
